version: "3.8"

services:
  # Backend Laravel
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: laravel-backend
    restart: unless-stopped
    volumes:
      - ./backend:/var/www
    networks:
      - app-network
    depends_on:
      - db

  # Nginx para Laravel
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - backend

  # Frontend Vue.js
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: vue-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network

  # Banco MySQL
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:

volumes:
  db_data: